#!/usr/bin/env python3
import ipaddress
import argparse
import string
def calip():
     parser = argparse.ArgumentParser()
     parser.add_argument('-a', '--address', type=str, default='address')
     args = parser.parse_args()
     if args is not None:
          ip_interface = ipaddress.ip_interface(f'{args.address}')
          print(f"IP-Adress: {ip_interface.ip}")
          print(f"Netmask: {ip_interface.netmask}")
          print(f"Bitmask: {ip_interface.network.prefixlen}")
          print(f"Next-network: {ip_interface.ip + 1}")
          print(f"End-network: {ip_interface.network.broadcast_address - 1}")
          print(f"Brodcast: {ip_interface.network.broadcast_address}")
          print(f"IP-address-network: {len(list(ip_interface.network.hosts()))}")
     else: 
          print("Please address format 0.0.0.0/00")

calip()
