#!/usr/bin/env bash
set -e 
GREEN='\e[32m' 
RED='\e[31m'
NORMAL='\e[0m' 
disk_list="/dev/sd*1 /dev/mapper/*-*"

for disk in $disk_list
do 
    
if [ ! -b $disk ]; then 
        echo "Disk $disk not found"
        continue 
fi

    fs_info=$(df -h $disk | tail -1)
    
if [ -z "$fs_info" ]; then 
         echo "No disk space information for $disk"
         continuef 
fi   
    disk_size=$(echo $fs_info | awk '{print $2}')
    disk_free=$(echo $fs_info | awk '{print $4}')
    disk_used=$(echo $fs_info | awk '{print $3}')
    disk_proc=$(echo $fs_info | awk '{print $5}')
    echo -e "DISK:${GREEN}$disk${NORMAL}"
    echo -e "Size=${GREEN}$disk_size${NORMAL}, Used=${GREEN}$disk_used${NORMAL}, Free=${GREEN}$disk_free${NORMAL}, Proc=${RED}$disk_proc${NORMAL}"
done 


exit 0
