#!/usr/bin/env bash
set -e
GREEN='\e[32m'
RED='\e[31m'
NORMAL='\e[0m'
size="80"
disk=$(df -h | grep /dev/loop)
disk_proc=$(echo $disk | awk '{print $5}')
disk_proc2=${disk_proc%%\%}
disk-free() {
   local disk_size=$( echo $disk | awk '{print $2}')
   local disk_free=$( echo $disk | awk '{print $4}')
   local disk_used=$( echo $disk | awk '{print $3}')
   local disk_proc=$( echo $disk | awk '{print $5}')
echo -e "Size=${GREEN}$disk_size${NORMAL}, Used=${GREEN}$disk_used${NORMAL}, Free=${GREEN}$disk_free${NORMAL}, Proc=${RED}$disk_proc${NORMAL}"
}
busy_disk() {
   local disk_size=$( echo $disk | awk '{print $2}')
   local disk_free=$( echo $disk | awk '{print $4}')
   local disk_used=$( echo $disk | awk '{print $3}')
   local disk_proc=$( echo $disk | awk '{print $5}')
	local HOMEDIR="/home/"
	local VARLOG="/var/log/"
echo "<=========$HOSTNAME===========>"
echo -e "Size=${GREEN}$disk_size${NORMAL}, Used=${GREEN}$disk_used${NORMAL}, Free=${GREEN}$disk_free${NORMAL}, Proc=${RED}$disk_proc${NORMAL}"
echo "<=============================>"
du -ahx ${HOMEDIR} | sort -rh | head -5
echo "<=============================>"
du -ahx ${VARLOG} | sort -rh | head -10
echo "<=============================>"
if [ ! -x /var/lib/docker ]; then
        echo -e "${G} There is no docker in the system ${O}"
else
        echo -e "${R} Log files size docker container ${O}"
        du -ahx /var/lib/docker/containers | sort -rh | head -10
fi
}
if [[ ${disk_proc2} > 80 ]]; then
	busy_disk
else
	disk-free
fi
